
################### English Navigation ########################
[[main]]
name = "about"
url = "#about"
weight = 1

[[main]]
name = "technology"
url = "#services"
weight = 2

[[main]]
name = "prototypes"
url = "#portfolio"
weight = 3

[[main]]
name = "impact"
url = "#feature"
weight = 4

[[main]]
name = "news"
url = "#blog"
weight = 5

[[main]]
name = "contact"
url = "#contact"
weight = 6
